"""Build a self-contained static site for free hosting (GitHub Pages).

    python -m scripts.build_static [--output site] [--engine chains]

The result is plain files: no Python, no server, nothing to keep running. Songs
are analysed at build time and baked into data.js, so the page is fully
interactive - hovering, tracing, isolating chains, switching between the
bundled songs - but cannot analyse anything new, because the phonetic engine is
Python and stays on the machine that ran this script.

That limitation is surfaced in the page rather than hidden: the build writes a
`RHYMEMAP_STATIC` flag which the viewer uses to explain itself and point at the
local install.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_ROOT / "web"

# Copied verbatim into the build. data.js is generated, not copied.
ASSETS = ("index.html", "style.css", "app.js", "effects.js")


def build(output: Path, engine: str, dataset: str, min_occurrences: int,
          include_demo: bool = True) -> int:
    from rhymemap.analyzer import DatasetError, iter_verses
    from rhymemap.cache import flush_all
    from rhymemap.webexport import analyse_text, verse_to_dict  # noqa: F401

    output.mkdir(parents=True, exist_ok=True)
    for name in ASSETS:
        source = WEB_DIR / name
        if not source.exists():
            print(f"error: missing {source}", file=sys.stderr)
            return 1
        shutil.copy2(source, output / name)

    verses = []

    demo = PROJECT_ROOT / "dataset" / "demo_rap_god.txt"
    if include_demo and demo.exists():
        print("  analysing the demo verse")
        verses.append(analyse_text(demo.read_text(encoding="utf-8"), "Eminem",
                                   "Rap God (full verse)", engine, min_occurrences))

    try:
        for track, artist, lyrics in iter_verses(dataset):
            print(f"  analysing {artist} - {track}")
            verses.append(analyse_text(lyrics, artist, track, engine, min_occurrences))
    except DatasetError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not verses:
        print("error: nothing to build", file=sys.stderr)
        return 1

    data = output / "data.js"
    with open(data, "w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/build_static.py. Do not edit.\n")
        handle.write("const RHYMEMAP_STATIC = true;\n")
        handle.write("const rhymeData = ")
        json.dump(verses, handle, ensure_ascii=False)
        handle.write(";\n")

    # Tell GitHub Pages not to run the output through Jekyll.
    (output / ".nojekyll").write_text("", encoding="utf-8")
    flush_all()

    size = sum(f.stat().st_size for f in output.rglob("*") if f.is_file()) / 1024
    print(f"\nbuilt {output}/ - {len(verses)} songs, {size:.0f} KB total")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", "-o", type=Path, default=PROJECT_ROOT / "site")
    parser.add_argument("--engine", "-e", default="chains",
                        help="engine to bake in (default: chains, which shows the most structure)")
    parser.add_argument("--dataset", default="dataset/artists_sample.csv")
    parser.add_argument("--min-occurrences", type=int, default=2)
    parser.add_argument("--no-demo", action="store_true")
    args = parser.parse_args(argv)

    print(f"building static site with the {args.engine} engine")
    return build(args.output, args.engine, args.dataset, args.min_occurrences,
                 include_demo=not args.no_demo)


if __name__ == "__main__":
    raise SystemExit(main())
