"""Derive the shipped Darija word list from the master lexicon.

``dataset/darija_lexicon_master_150k.csv`` is 61 MB of provenance: surface
form, script, parent form, derivation rule, source URL, review status. The
engine needs one column of it -- the Latin-script spellings -- so the runtime
reads a plain word list built here instead of parsing the master on every boot.
That also keeps the master out of the Docker image, where 61 MB of CSV would be
paid for on every cold start of a free tier that sleeps.

Two filters, both of which matter:

**Script.** Only ``latin`` and ``latin_arabizi`` rows are usable. The Arabic
script rows are the same words in an alphabet the Arabizi G2P cannot read.

**CMUdict.** Any spelling English already has a pronunciation for is dropped.
These are almost entirely loanwords Darija took from French and English --
album, bus, business, camera, bracelet -- where CMUdict is the better answer
anyway. Dropping them is what makes the list safe to trust over CMUdict at
lookup time, which in turn is what lets it drive language detection.

Run it with::

    python -m scripts.build_darija_lexicon
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MASTER = PROJECT_ROOT / "dataset" / "darija_lexicon_master_150k.csv"
OUTPUT = PROJECT_ROOT / "rhymemap" / "data" / "darija_words.txt"

LATIN_SCRIPTS = {"latin", "latin_arabizi"}

# What the Arabizi G2P can actually read: letters plus the five Arabizi digits.
READABLE = re.compile(r"^[a-z23579]{2,}$")

ATTRIBUTION = """\
# Moroccan Darija word list for RhymeMapper.
#
# Generated by scripts/build_darija_lexicon.py from
# dataset/darija_lexicon_master_150k.csv -- do not edit by hand.
#
# Latin-script surface forms only, with every spelling CMUdict already knows
# removed so the list can be trusted ahead of the English dictionary.
#
# Source: seeded and guided by the Darija Open Dataset (DODa),
# https://github.com/darija-open-dataset/dataset, CC BY-NC 4.0.
# Generated morphological candidates are rule-derived, not corpus-attested.
"""


def build(master: Path = MASTER, output: Path = OUTPUT) -> int:
    if not master.is_file():
        print(f"missing {master}", file=sys.stderr)
        return 0

    from rhymemap.phonetics import _syllabify_one

    csv.field_size_limit(10 ** 7)
    forms: set[str] = set()
    total = 0
    with master.open(newline="", encoding="utf-8-sig", errors="replace") as handle:
        for row in csv.DictReader(handle):
            total += 1
            if row.get("script") not in LATIN_SCRIPTS:
                continue
            word = (row.get("surface_form") or "").strip().lower()
            if READABLE.match(word):
                forms.add(word)

    readable = len(forms)
    forms = {w for w in forms if not _syllabify_one(w)}

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(ATTRIBUTION + "\n".join(sorted(forms)) + "\n", encoding="utf-8")

    print(f"{total} rows -> {readable} readable Latin forms -> "
          f"{len(forms)} kept ({readable - len(forms)} already in CMUdict)")
    print(f"wrote {output.relative_to(PROJECT_ROOT)} "
          f"({output.stat().st_size / 1e6:.1f} MB)")
    return len(forms)


if __name__ == "__main__":
    raise SystemExit(0 if build() else 1)
